export const products = [
	{
		id: 1,
		title: "Wireless Headphones",
		description: "Noise-cancelling over-ear headphones with 30h battery life.",
		img: "https://s13emagst.akamaized.net/products/53458/53457332/images/res_64cc3ef89a16222a64d98161215c6243.jpg?width=720&height=720&hash=333ACB48E583DF291926E003863AE0F7",
		price: 199,
	},
	{
		id: 2,
		title: "Smartwatch Fit+",
		description: "Fitness tracking smartwatch with heart rate monitor and GPS.",
		img: "https://m.media-amazon.com/images/I/71GsDAbysoL._AC_UY327_FMwebp_QL65_.jpg",
		price: 249,
	},
	{
		id: 3,
		title: "Mechanical Keyboard",
		description: "RGB backlit mechanical keyboard with customizable switches.",
		img: "https://m.media-amazon.com/images/I/61XogzWL2zL._AC_UY327_FMwebp_QL65_.jpg",
		price: 129,
	},
	{
		id: 4,
		title: "Wireless Mouse",
		description: "Ergonomic wireless mouse with ultra-precise tracking.",
		img: "https://m.media-amazon.com/images/I/61l5dMnGNBL._AC_UY327_FMwebp_QL65_.jpg",
		price: 49,
	},
	{
		id: 5,
		title: "Tablet S12",
		description: "Lightweight tablet with 12-inch Retina display and stylus support.",
		img: "https://m.media-amazon.com/images/I/61d46oYQgdL._AC_UY327_FMwebp_QL65_.jpg",
		price: 699,
	},
	{
		id: 6,
		title: "External SSD 1TB",
		description: "High-speed portable SSD with 1TB storage capacity.",
		img: "https://m.media-amazon.com/images/I/51Aexv0GWML._AC_UY327_FMwebp_QL65_.jpg",
		price: 149,
	},
	{
		id: 7,
		title: "Gaming Headset",
		description: "Surround sound headset with microphone for gaming and streaming.",
		img: "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_UY327_FMwebp_QL65_.jpg",
		price: 89,
	},
	{
		id: 8,
		title: "Bluetooth Speaker",
		description: "Portable waterproof Bluetooth speaker with powerful sound.",
		img: "https://m.media-amazon.com/images/I/81l7mB5LhsL._AC_UY327_FMwebp_QL65_.jpg",
		price: 59,
	},
	{
		id: 9,
		title: "Smartphone Stand",
		description: "Adjustable aluminum stand for phones and tablets.",
		img: "https://m.media-amazon.com/images/I/518AlpsFbEL._AC_UY327_FMwebp_QL65_.jpg",
		price: 19,
	},
	{
		id: 10,
		title: "Wireless Charger",
		description: "Fast wireless charging pad compatible with all smartphones.",
		img: "https://m.media-amazon.com/images/I/61VwfUI+-eL._AC_UY327_FMwebp_QL65_.jpg",
		price: 29,
	},
	{
		id: 11,
		title: 'External Monitor 24"',
		description: "Full HD 24-inch external monitor for office and gaming.",
		img: "https://m.media-amazon.com/images/I/71hI7La85FL._AC_UY327_FMwebp_QL65_.jpg",
		price: 199,
	},
	{
		id: 12,
		title: "Wireless Headphones",
		description: "Noise-cancelling over-ear headphones with 30h battery life.",
		img: "https://s13emagst.akamaized.net/products/53458/53457332/images/res_64cc3ef89a16222a64d98161215c6243.jpg?width=720&height=720&hash=333ACB48E583DF291926E003863AE0F7",
		price: 199,
	},
	{
		id: 13,
		title: "Smartwatch Fit+",
		description: "Fitness tracking smartwatch with heart rate monitor and GPS.",
		img: "https://m.media-amazon.com/images/I/71GsDAbysoL._AC_UY327_FMwebp_QL65_.jpg",
		price: 249,
	},
	{
		id: 14,
		title: "Mechanical Keyboard",
		description: "RGB backlit mechanical keyboard with customizable switches.",
		img: "https://m.media-amazon.com/images/I/61XogzWL2zL._AC_UY327_FMwebp_QL65_.jpg",
		price: 129,
	},
	{
		id: 15,
		title: "Wireless Mouse",
		description: "Ergonomic wireless mouse with ultra-precise tracking.",
		img: "https://m.media-amazon.com/images/I/61l5dMnGNBL._AC_UY327_FMwebp_QL65_.jpg",
		price: 49,
	},
	{
		id: 16,
		title: "Tablet S12",
		description: "Lightweight tablet with 12-inch Retina display and stylus support.",
		img: "https://m.media-amazon.com/images/I/61d46oYQgdL._AC_UY327_FMwebp_QL65_.jpg",
		price: 699,
	},
	{
		id: 17,
		title: "External SSD 1TB",
		description: "High-speed portable SSD with 1TB storage capacity.",
		img: "https://m.media-amazon.com/images/I/51Aexv0GWML._AC_UY327_FMwebp_QL65_.jpg",
		price: 149,
	},
	{
		id: 18,
		title: "Gaming Headset",
		description: "Surround sound headset with microphone for gaming and streaming.",
		img: "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_UY327_FMwebp_QL65_.jpg",
		price: 89,
	},
	{
		id: 19,
		title: "Bluetooth Speaker",
		description: "Portable waterproof Bluetooth speaker with powerful sound.",
		img: "https://m.media-amazon.com/images/I/81l7mB5LhsL._AC_UY327_FMwebp_QL65_.jpg",
		price: 59,
	},
	{
		id: 20,
		title: "Smartphone Stand",
		description: "Adjustable aluminum stand for phones and tablets.",
		img: "https://m.media-amazon.com/images/I/518AlpsFbEL._AC_UY327_FMwebp_QL65_.jpg",
		price: 19,
	},
	{
		id: 21,
		title: "Wireless Charger",
		description: "Fast wireless charging pad compatible with all smartphones.",
		img: "https://m.media-amazon.com/images/I/61VwfUI+-eL._AC_UY327_FMwebp_QL65_.jpg",
		price: 29,
	},
	{
		id: 22,
		title: 'External Monitor 24"',
		description: "Full HD 24-inch external monitor for office and gaming.",
		img: "https://m.media-amazon.com/images/I/71hI7La85FL._AC_UY327_FMwebp_QL65_.jpg",
		price: 199,
	},
	{
		id: 23,
		title: "Wireless Headphones",
		description: "Noise-cancelling over-ear headphones with 30h battery life.",
		img: "https://s13emagst.akamaized.net/products/53458/53457332/images/res_64cc3ef89a16222a64d98161215c6243.jpg?width=720&height=720&hash=333ACB48E583DF291926E003863AE0F7",
		price: 199,
	},
	{
		id: 24,
		title: "Smartwatch Fit+",
		description: "Fitness tracking smartwatch with heart rate monitor and GPS.",
		img: "https://m.media-amazon.com/images/I/71GsDAbysoL._AC_UY327_FMwebp_QL65_.jpg",
		price: 249,
	},
	{
		id: 25,
		title: "Mechanical Keyboard",
		description: "RGB backlit mechanical keyboard with customizable switches.",
		img: "https://m.media-amazon.com/images/I/61XogzWL2zL._AC_UY327_FMwebp_QL65_.jpg",
		price: 129,
	},
	{
		id: 26,
		title: "Wireless Mouse",
		description: "Ergonomic wireless mouse with ultra-precise tracking.",
		img: "https://m.media-amazon.com/images/I/61l5dMnGNBL._AC_UY327_FMwebp_QL65_.jpg",
		price: 49,
	},
	{
		id: 27,
		title: "Tablet S12",
		description: "Lightweight tablet with 12-inch Retina display and stylus support.",
		img: "https://m.media-amazon.com/images/I/61d46oYQgdL._AC_UY327_FMwebp_QL65_.jpg",
		price: 699,
	},
	{
		id: 28,
		title: "External SSD 1TB",
		description: "High-speed portable SSD with 1TB storage capacity.",
		img: "https://m.media-amazon.com/images/I/51Aexv0GWML._AC_UY327_FMwebp_QL65_.jpg",
		price: 149,
	},
	{
		id: 29,
		title: "Gaming Headset",
		description: "Surround sound headset with microphone for gaming and streaming.",
		img: "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_UY327_FMwebp_QL65_.jpg",
		price: 89,
	},
	{
		id: 30,
		title: "Bluetooth Speaker",
		description: "Portable waterproof Bluetooth speaker with powerful sound.",
		img: "https://m.media-amazon.com/images/I/81l7mB5LhsL._AC_UY327_FMwebp_QL65_.jpg",
		price: 59,
	},
	{
		id: 31,
		title: "Smartphone Stand",
		description: "Adjustable aluminum stand for phones and tablets.",
		img: "https://m.media-amazon.com/images/I/518AlpsFbEL._AC_UY327_FMwebp_QL65_.jpg",
		price: 19,
	},
	{
		id: 32,
		title: "Wireless Charger",
		description: "Fast wireless charging pad compatible with all smartphones.",
		img: "https://m.media-amazon.com/images/I/61VwfUI+-eL._AC_UY327_FMwebp_QL65_.jpg",
		price: 29,
	},
	{
		id: 33,
		title: 'External Monitor 24"',
		description: "Full HD 24-inch external monitor for office and gaming.",
		img: "https://m.media-amazon.com/images/I/71hI7La85FL._AC_UY327_FMwebp_QL65_.jpg",
		price: 199,
	},
	{
		id: 34,
		title: "Wireless Headphones",
		description: "Noise-cancelling over-ear headphones with 30h battery life.",
		img: "https://s13emagst.akamaized.net/products/53458/53457332/images/res_64cc3ef89a16222a64d98161215c6243.jpg?width=720&height=720&hash=333ACB48E583DF291926E003863AE0F7",
		price: 199,
	},
	{
		id: 35,
		title: "Smartwatch Fit+",
		description: "Fitness tracking smartwatch with heart rate monitor and GPS.",
		img: "https://m.media-amazon.com/images/I/71GsDAbysoL._AC_UY327_FMwebp_QL65_.jpg",
		price: 249,
	},
	{
		id: 36,
		title: "Mechanical Keyboard",
		description: "RGB backlit mechanical keyboard with customizable switches.",
		img: "https://m.media-amazon.com/images/I/61XogzWL2zL._AC_UY327_FMwebp_QL65_.jpg",
		price: 129,
	},
	{
		id: 37,
		title: "Wireless Mouse",
		description: "Ergonomic wireless mouse with ultra-precise tracking.",
		img: "https://m.media-amazon.com/images/I/61l5dMnGNBL._AC_UY327_FMwebp_QL65_.jpg",
		price: 49,
	},
	{
		id: 38,
		title: "Tablet S12",
		description: "Lightweight tablet with 12-inch Retina display and stylus support.",
		img: "https://m.media-amazon.com/images/I/61d46oYQgdL._AC_UY327_FMwebp_QL65_.jpg",
		price: 699,
	},
	{
		id: 39,
		title: "External SSD 1TB",
		description: "High-speed portable SSD with 1TB storage capacity.",
		img: "https://m.media-amazon.com/images/I/51Aexv0GWML._AC_UY327_FMwebp_QL65_.jpg",
		price: 149,
	},
	{
		id: 40,
		title: "Gaming Headset",
		description: "Surround sound headset with microphone for gaming and streaming.",
		img: "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_UY327_FMwebp_QL65_.jpg",
		price: 89,
	},
	{
		id: 41,
		title: "Bluetooth Speaker",
		description: "Portable waterproof Bluetooth speaker with powerful sound.",
		img: "https://m.media-amazon.com/images/I/81l7mB5LhsL._AC_UY327_FMwebp_QL65_.jpg",
		price: 59,
	},
	{
		id: 42,
		title: "Smartphone Stand",
		description: "Adjustable aluminum stand for phones and tablets.",
		img: "https://m.media-amazon.com/images/I/518AlpsFbEL._AC_UY327_FMwebp_QL65_.jpg",
		price: 19,
	},
	{
		id: 43,
		title: "Wireless Charger",
		description: "Fast wireless charging pad compatible with all smartphones.",
		img: "https://m.media-amazon.com/images/I/61VwfUI+-eL._AC_UY327_FMwebp_QL65_.jpg",
		price: 29,
	},
	{
		id: 44,
		title: 'External Monitor 24"',
		description: "Full HD 24-inch external monitor for office and gaming.",
		img: "https://m.media-amazon.com/images/I/71hI7La85FL._AC_UY327_FMwebp_QL65_.jpg",
		price: 199,
	},
	{
		id: 45,
		title: "Wireless Headphones",
		description: "Noise-cancelling over-ear headphones with 30h battery life.",
		img: "https://s13emagst.akamaized.net/products/53458/53457332/images/res_64cc3ef89a16222a64d98161215c6243.jpg?width=720&height=720&hash=333ACB48E583DF291926E003863AE0F7",
		price: 199,
	},
	{
		id: 46,
		title: "Smartwatch Fit+",
		description: "Fitness tracking smartwatch with heart rate monitor and GPS.",
		img: "https://m.media-amazon.com/images/I/71GsDAbysoL._AC_UY327_FMwebp_QL65_.jpg",
		price: 249,
	},
	{
		id: 47,
		title: "Mechanical Keyboard",
		description: "RGB backlit mechanical keyboard with customizable switches.",
		img: "https://m.media-amazon.com/images/I/61XogzWL2zL._AC_UY327_FMwebp_QL65_.jpg",
		price: 129,
	},
	{
		id: 4,
		title: "Wireless Mouse",
		description: "Ergonomic wireless mouse with ultra-precise tracking.",
		img: "https://m.media-amazon.com/images/I/61l5dMnGNBL._AC_UY327_FMwebp_QL65_.jpg",
		price: 49,
	},
	{
		id: 48,
		title: "Tablet S12",
		description: "Lightweight tablet with 12-inch Retina display and stylus support.",
		img: "https://m.media-amazon.com/images/I/61d46oYQgdL._AC_UY327_FMwebp_QL65_.jpg",
		price: 699,
	},
	{
		id: 49,
		title: "External SSD 1TB",
		description: "High-speed portable SSD with 1TB storage capacity.",
		img: "https://m.media-amazon.com/images/I/51Aexv0GWML._AC_UY327_FMwebp_QL65_.jpg",
		price: 149,
	},
	{
		id: 50,
		title: "Gaming Headset",
		description: "Surround sound headset with microphone for gaming and streaming.",
		img: "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_UY327_FMwebp_QL65_.jpg",
		price: 89,
	},
	{
		id: 51,
		title: "Bluetooth Speaker",
		description: "Portable waterproof Bluetooth speaker with powerful sound.",
		img: "https://m.media-amazon.com/images/I/81l7mB5LhsL._AC_UY327_FMwebp_QL65_.jpg",
		price: 59,
	},
	{
		id: 52,
		title: "Smartphone Stand",
		description: "Adjustable aluminum stand for phones and tablets.",
		img: "https://m.media-amazon.com/images/I/518AlpsFbEL._AC_UY327_FMwebp_QL65_.jpg",
		price: 19,
	},
	{
		id: 53,
		title: "Wireless Charger",
		description: "Fast wireless charging pad compatible with all smartphones.",
		img: "https://m.media-amazon.com/images/I/61VwfUI+-eL._AC_UY327_FMwebp_QL65_.jpg",
		price: 29,
	},
	{
		id: 54,
		title: 'External Monitor 24"',
		description: "Full HD 24-inch external monitor for office and gaming.",
		img: "https://m.media-amazon.com/images/I/71hI7La85FL._AC_UY327_FMwebp_QL65_.jpg",
		price: 199,
	},
	{
		id: 55,
		title: "Wireless Headphones",
		description: "Noise-cancelling over-ear headphones with 30h battery life.",
		img: "https://s13emagst.akamaized.net/products/53458/53457332/images/res_64cc3ef89a16222a64d98161215c6243.jpg?width=720&height=720&hash=333ACB48E583DF291926E003863AE0F7",
		price: 199,
	},
	{
		id: 56,
		title: "Smartwatch Fit+",
		description: "Fitness tracking smartwatch with heart rate monitor and GPS.",
		img: "https://m.media-amazon.com/images/I/71GsDAbysoL._AC_UY327_FMwebp_QL65_.jpg",
		price: 249,
	},
	{
		id: 57,
		title: "Mechanical Keyboard",
		description: "RGB backlit mechanical keyboard with customizable switches.",
		img: "https://m.media-amazon.com/images/I/61XogzWL2zL._AC_UY327_FMwebp_QL65_.jpg",
		price: 129,
	},
	{
		id: 59,
		title: "Wireless Mouse",
		description: "Ergonomic wireless mouse with ultra-precise tracking.",
		img: "https://m.media-amazon.com/images/I/61l5dMnGNBL._AC_UY327_FMwebp_QL65_.jpg",
		price: 49,
	},
	{
		id: 70,
		title: "Tablet S12",
		description: "Lightweight tablet with 12-inch Retina display and stylus support.",
		img: "https://m.media-amazon.com/images/I/61d46oYQgdL._AC_UY327_FMwebp_QL65_.jpg",
		price: 699,
	},
	{
		id: 71,
		title: "External SSD 1TB",
		description: "High-speed portable SSD with 1TB storage capacity.",
		img: "https://m.media-amazon.com/images/I/51Aexv0GWML._AC_UY327_FMwebp_QL65_.jpg",
		price: 149,
	},
	{
		id: 72,
		title: "Gaming Headset",
		description: "Surround sound headset with microphone for gaming and streaming.",
		img: "https://m.media-amazon.com/images/I/61CGHv6kmWL._AC_UY327_FMwebp_QL65_.jpg",
		price: 89,
	},
	{
		id: 73,
		title: "Bluetooth Speaker",
		description: "Portable waterproof Bluetooth speaker with powerful sound.",
		img: "https://m.media-amazon.com/images/I/81l7mB5LhsL._AC_UY327_FMwebp_QL65_.jpg",
		price: 59,
	},
	{
		id: 74,
		title: "Smartphone Stand",
		description: "Adjustable aluminum stand for phones and tablets.",
		img: "https://m.media-amazon.com/images/I/518AlpsFbEL._AC_UY327_FMwebp_QL65_.jpg",
		price: 19,
	},
	{
		id: 75,
		title: "Wireless Charger",
		description: "Fast wireless charging pad compatible with all smartphones.",
		img: "https://m.media-amazon.com/images/I/61VwfUI+-eL._AC_UY327_FMwebp_QL65_.jpg",
		price: 29,
	},
	{
		id: 76,
		title: 'External Monitor 24"',
		description: "Full HD 24-inch external monitor for office and gaming.",
		img: "https://m.media-amazon.com/images/I/71hI7La85FL._AC_UY327_FMwebp_QL65_.jpg",
		price: 199,
	},
];
